### ISSUE TITLE
database user for api

### ISSUE THREAD

**Issue by barrytam20** [OrcaCollective/spd-lookup#7]
Currently, both api and db services are using the same credentials, meaning the api is actually using the admin role for the db. Not really a security issue at the moment, since we dont allow the api to make adhoc queries, and the db credentials are removed after a deployment.  

Ideally, we should create a database user for each service accessing the database, and keep the admin credentials somewhere safe

**Comment by mpuckett159** [comment]
tbh I don't think this is strictly necessary. The data isn't really ephemeral (it's not at risk of being lost) and the database isn't exposed in anyway to external users outside of the fact that the api container can talk to the db container. I think the only reason we would be worried is if we intended to allow external users to make updates/changes to the data we hosted but I don't see that being the case. We can re-open in the future if it's necessary.
